# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.runs/synth_1/rvfpganexys.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.cache/wt [current_project]
set_property parent.project_path /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/pnevins/.Xilinx/Vivado/2022.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.2 [current_project]
set_property ip_output_repo /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include
} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/include/common_defines.vh
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/gpio/gpio_defines.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/ptc/ptc_defines.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_params.vh
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/uart/uart_defines.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/typedef.svh
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/assign.svh
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells/registers.svh
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_param.vh
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/include/pic_map_auto.h
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/WishboneInterconnect/wb_intercon.vh
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/axi_intercon.vh
}
set_property is_global_include true [get_files /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/include/common_defines.vh]
set_property file_type "Verilog Header" [get_files /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/gpio/gpio_defines.v]
set_property file_type "Verilog Header" [get_files /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/ptc/ptc_defines.v]
set_property file_type "Verilog Header" [get_files /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/uart/uart_defines.v]
set_property file_type "Verilog Header" [get_files /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/typedef.svh]
set_property file_type "Verilog Header" [get_files /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/assign.svh]
set_property file_type "Verilog Header" [get_files /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells/registers.svh]
set_property file_type "Verilog Header" [get_files /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/include/pic_map_auto.h]
read_mem /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.srcs/sources_1/imports/sw/boot_main.mem
read_verilog -library xil_defaultlib -sv {
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_pdef.vh
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/cf_math_pkg.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/addr_decode.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_pkg.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_cdc.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_demux.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_err_slv.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_id_prepend.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/axi_intercon.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_intf.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_mux.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_xbar.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lib/beh_lib.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/binary_to_gray.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/bscan_tap.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/cdc_fifo_gray.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/counter.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/delta_counter.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_def.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/dbg/el2_dbg.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_decode_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_gpr_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_ib_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_tlu_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_trigger.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/el2_dma_ctrl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/exu/el2_exu.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/exu/el2_exu_alu_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/exu/el2_exu_div_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/exu/el2_exu_mul_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_aln_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_bp_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_compress_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_ic_mem.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_iccm_mem.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_ifc_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_mem_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lib/el2_lib.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_addrcheck.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_bus_buffer.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_bus_intf.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_clkdomain.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_dccm_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_dccm_mem.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_ecc.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_lsc_ctl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_stbuf.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_trigger.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/el2_mem.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/el2_pic_ctrl.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/el2_veer.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/fifo_v3.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/gray_to_binary.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/lzc.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/lib/mem_lib.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/rr_arb_tree.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/spill_register.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/sync.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/veer_el2_wrapper.sv
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/veerwolf_core.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/SystemController/veerwolf_syscon.sv
  /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.srcs/sources_1/imports/vga/vga.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/rvfpganexys.sv
}
set_property file_type SystemVerilog [get_files /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_pdef.vh]
set_property is_global_include true [get_files /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_pdef.vh]
read_verilog -library xil_defaultlib {
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/AxiToWb/axi2wb.v
  /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.srcs/sources_1/imports/vga/char_rom.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/OtherSources/clk_gen_nexys.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/BootROM/dpram64.v
  /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.srcs/sources_1/imports/vga/dtg.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/spi/fifo4.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/gpio/gpio_top.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/litedram_core.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/litedram_top.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/ptc/ptc_top.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/uart/raminfr.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_alu.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_bufreg.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_csr.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_ctrl.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_decode.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_mem_if.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_if.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_ram.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_ram_if.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_rf_top.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_shift.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_state.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/serv_1.0.2/rtl/serv_top.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/spi/simple_spi_top.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/uart/uart_receiver.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/uart/uart_regs.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/uart/uart_rfifo.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/uart/uart_sync_flops.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/uart/uart_tfifo.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/uart/uart_top.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/uart/uart_transmitter.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Peripherals/uart/uart_wb.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/WishboneInterconnect/wb_intercon.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/BootROM/wb_mem_wrapper.v
  /home/pnevins/College/ECE-540/Project2/RVfpga_NexysA7-DDR/src/VeeRwolf/Interconnect/WishboneInterconnect/wb_intercon_1.2.2-r1/rtl/verilog/wb_mux.v
}
read_ip -quiet /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.srcs/constrs_1/imports/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/liteDRAM.xdc
set_property used_in_implementation false [get_files /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.srcs/constrs_1/imports/ECE-540/Project2/RVfpga_NexysA7-DDR/src/LiteDRAM/liteDRAM.xdc]

read_xdc /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.srcs/constrs_1/imports/ECE-540/saicode/new/rvfpganexys.xdc
set_property used_in_implementation false [get_files /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.srcs/constrs_1/imports/ECE-540/saicode/new/rvfpganexys.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/pnevins/College/ECE-540/Project2/VivadoWS/VGA_Proj2/VGA_Proj2.srcs/utils_1/imports/synth_1/rvfpganexys.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top rvfpganexys -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rvfpganexys.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rvfpganexys_utilization_synth.rpt -pb rvfpganexys_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
